### ISSUE TITLE
Fail to train with default parameters

### ISSUE THREAD

**Issue by ArmanChopikyan** [mohamedkeid/Neural-Image-Colorization#1]
I run model with following parameters
dataset size = 5800 image
image size = 256 x 256 x 3 
iteration count = 82000 
and below is my result 
descriminator loss  = -21612.7519531250
generator loss        =  33281.8437500000
![out_1490255538](https://cloud.githubusercontent.com/assets/26434373/24237345/5978ac06-0fbf-11e7-9d9b-68fca29eaeb3.jpg)
WHY?

**Comment by mohamedkeid** [comment]
The size of you dataset is far too small for this thing to learn how to generalize. I recommend at least ~1 million images. The number of iterations should also be significantly greater. This is not a short training session.
