### ISSUE TITLE
Variable does not exist

### ISSUE THREAD

**Issue by Tranvick** [mohamedkeid/Neural-Image-Colorization#2]
I always get this and don't know how to fix it. Could you provide any suggestions? tensorflow-1.1.0

> 
ValueError: Variable discriminator/conv1/batch_normalization/moments_5/Squeeze/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by mohamedkeid** [comment]
Hey! That's a Tensorflow 1.1 related problem. I'm not sure what they
changed but the hack commonly used to reuse variables with an EMA no longer
works.

**Comment by mohamedkeid** [comment]
That's a TensorFlow 1.1 related problem. I'm not sure what they changed but the hack commonly used to reuse variables with an EMA no longer works.
